name: SER Sandbox Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sandbox-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests

      - name: Start Flask server
        run: |
          nohup python ser.py &
          sleep 5

      - name: Run SER API test
        run: |
          curl -X POST http://127.0.0.1:8080/ser \
          -H "Content-Type: application/json" \
          -d '{"nodes":[{"energy":1},{"energy":2}],"prob":[0.5,0.5]}'