name: Test SER Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install flask requests

      - name: Run SER API test
        run: |
          nohup python ser.py &
          sleep 5
          RESPONSE=$(curl -s -X POST http://127.0.0.1:8080/ser \
            -H "Content-Type: application/json" \
            -d '{"nodes":[{"energy":1},{"energy":2}],"prob":[0.5,0.5]}')
          echo "Response: $RESPONSE"
          python - <<'PYCODE'
import json, sys
d = json.loads("""$RESPONSE""")
if d.get("H") != 3:
    sys.exit(f"❌ Expected H=3 but got {d}")
print("✅ SER API test passed successfully!")
PYCODE